// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8lJa79Z2_npn0XhnGwzUN8X3GzbikfJQ',
    appId: '1:528592506935:web:541783257c602033556fb2',
    messagingSenderId: '528592506935',
    projectId: 'fineasy-3a2ce',
    authDomain: 'fineasy-3a2ce.firebaseapp.com',
    storageBucket: 'fineasy-3a2ce.firebasestorage.app',
    measurementId: 'G-4EH0T6DQ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7gjGxmITBZmYWbCByANRc6xorGkYjDzk',
    appId: '1:528592506935:android:f0ab2ca7ded8bea0556fb2',
    messagingSenderId: '528592506935',
    projectId: 'fineasy-3a2ce',
    storageBucket: 'fineasy-3a2ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2wBGAUusyAbJtk_E2MP3hWL02dkWOdm0',
    appId: '1:528592506935:ios:a2ca81e36a8c1711556fb2',
    messagingSenderId: '528592506935',
    projectId: 'fineasy-3a2ce',
    storageBucket: 'fineasy-3a2ce.firebasestorage.app',
    iosBundleId: 'com.shailendra.fineasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2wBGAUusyAbJtk_E2MP3hWL02dkWOdm0',
    appId: '1:528592506935:ios:df364ea0f482c31a556fb2',
    messagingSenderId: '528592506935',
    projectId: 'fineasy-3a2ce',
    storageBucket: 'fineasy-3a2ce.firebasestorage.app',
    iosBundleId: 'com.example.fineasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8lJa79Z2_npn0XhnGwzUN8X3GzbikfJQ',
    appId: '1:528592506935:web:681534a938ee0984556fb2',
    messagingSenderId: '528592506935',
    projectId: 'fineasy-3a2ce',
    authDomain: 'fineasy-3a2ce.firebaseapp.com',
    storageBucket: 'fineasy-3a2ce.firebasestorage.app',
    measurementId: 'G-5PNDSKW7KL',
  );
}
